import React from 'react';
import { Document, Page, Text, View, Image } from '@react-pdf/renderer';
import { styles } from './styles.js';
import { formatMoney } from './formatMoney.js';
import type { IInvoice } from '../../models/Invoice.js';

interface Props {
  invoice: IInvoice & { client: { name: string; contactPerson?: string; email?: string; address?: string } };
}

export function InvoicePDF({ invoice: inv }: Props) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <View>
            <Text style={styles.companyName}>Naton Lab Limited</Text>
          </View>
          <View>
            <Text style={styles.docTitle}>INVOICE</Text>
            <Text style={styles.docNumber}>{inv.invoiceNumber}</Text>
            <Text style={styles.docNumber}>{new Date(inv.createdAt).toLocaleDateString()}</Text>
          </View>
        </View>

        <View>
          <Text style={styles.sectionTitle}>Bill To</Text>
          <Text style={styles.bold}>{inv.client.name}</Text>
          {inv.client.contactPerson && <Text>{inv.client.contactPerson}</Text>}
          {inv.client.email && <Text>{inv.client.email}</Text>}
          {inv.client.address && <Text>{inv.client.address}</Text>}
        </View>

        {inv.milestone && (
          <View style={{ marginTop: 10 }}>
            <Text style={{ color: '#666' }}>Milestone: {inv.milestone}</Text>
          </View>
        )}

        {inv.dueDate && (
          <View style={{ marginTop: 4 }}>
            <Text style={{ color: '#666' }}>Due Date: {new Date(inv.dueDate).toLocaleDateString()}</Text>
          </View>
        )}

        <View style={[styles.table, { marginTop: 16 }]}>
          <View style={styles.tableHeader}>
            <Text style={[styles.colDesc, styles.bold]}>Description</Text>
            <Text style={[styles.colQty, styles.bold]}>Qty</Text>
            <Text style={[styles.colPrice, styles.bold]}>Unit Price</Text>
            <Text style={[styles.colAmount, styles.bold]}>Amount</Text>
          </View>
          {inv.lineItems.map((item, i) => (
            <View key={i} style={styles.tableRow}>
              <Text style={styles.colDesc}>{item.description}</Text>
              <Text style={styles.colQty}>{item.quantity}</Text>
              <Text style={styles.colPrice}>{formatMoney(item.unitPrice)}</Text>
              <Text style={styles.colAmount}>{formatMoney(item.amount)}</Text>
            </View>
          ))}
        </View>

        <View style={{ marginTop: 10 }}>
          <View style={styles.totalsRow}>
            <Text style={styles.totalsLabel}>Subtotal:</Text>
            <Text style={styles.totalsValue}>{formatMoney(inv.subtotal)}</Text>
          </View>
          {inv.discount > 0 && (
            <View style={styles.totalsRow}>
              <Text style={styles.totalsLabel}>Discount:</Text>
              <Text style={styles.totalsValue}>-{formatMoney(inv.discount)}</Text>
            </View>
          )}
          <View style={[styles.totalsRow, { marginTop: 4 }]}>
            <Text style={[styles.totalsLabel, styles.totalFinal]}>Total:</Text>
            <Text style={[styles.totalsValue, styles.totalFinal]}>{formatMoney(inv.total)}</Text>
          </View>
          {inv.amountPaid > 0 && (
            <>
              <View style={styles.totalsRow}>
                <Text style={styles.totalsLabel}>Paid:</Text>
                <Text style={styles.totalsValue}>{formatMoney(inv.amountPaid)}</Text>
              </View>
              <View style={styles.totalsRow}>
                <Text style={[styles.totalsLabel, styles.bold]}>Amount Due:</Text>
                <Text style={[styles.totalsValue, styles.bold]}>{formatMoney(inv.amountDue)}</Text>
              </View>
            </>
          )}
        </View>

        {inv.notes && (
          <View style={{ marginTop: 16 }}>
            <Text style={styles.sectionTitle}>Notes</Text>
            <Text>{inv.notes}</Text>
          </View>
        )}

        {(inv.companyChopUrl || inv.signatureUrl) && (
          <View style={styles.signatureArea}>
            {inv.companyChopUrl && (
              <View>
                <Text style={{ marginBottom: 4, color: '#666' }}>Company Chop</Text>
                <Image src={inv.companyChopUrl} style={styles.stampImage} />
              </View>
            )}
            {inv.signatureUrl && (
              <View>
                <Text style={{ marginBottom: 4, color: '#666' }}>Authorized Signature</Text>
                <Image src={inv.signatureUrl} style={styles.sigImage} />
              </View>
            )}
          </View>
        )}

        <Text style={styles.footer}>Generated by HateBookkeeping</Text>
      </Page>
    </Document>
  );
}
