import React from 'react';
import { Document, Page, Text, View, Image } from '@react-pdf/renderer';
import { styles } from './styles.js';
import { formatMoney } from './formatMoney.js';
import type { IReceipt } from '../../models/Receipt.js';
import type { IInvoice } from '../../models/Invoice.js';

interface Props {
  receipt: IReceipt & {
    client: { name: string; contactPerson?: string };
    invoice: IInvoice;
  };
}

export function ReceiptPDF({ receipt: r }: Props) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <View>
            <Text style={styles.companyName}>Naton Lab Limited</Text>
          </View>
          <View>
            <Text style={styles.docTitle}>RECEIPT</Text>
            <Text style={styles.docNumber}>{r.receiptNumber}</Text>
            <Text style={styles.docNumber}>{new Date(r.paymentDate).toLocaleDateString()}</Text>
          </View>
        </View>

        <View>
          <Text style={styles.sectionTitle}>Received From</Text>
          <Text style={styles.bold}>{r.client.name}</Text>
          {r.client.contactPerson && <Text>{r.client.contactPerson}</Text>}
        </View>

        <View style={{ marginTop: 20 }}>
          <View style={styles.infoRow}>
            <Text style={styles.infoLabel}>Invoice:</Text>
            <Text style={styles.infoValue}>{r.invoice?.invoiceNumber || ''}</Text>
          </View>
          <View style={styles.infoRow}>
            <Text style={styles.infoLabel}>Amount:</Text>
            <Text style={[styles.infoValue, styles.bold, { fontSize: 14 }]}>{formatMoney(r.amount)}</Text>
          </View>
          <View style={styles.infoRow}>
            <Text style={styles.infoLabel}>Method:</Text>
            <Text style={styles.infoValue}>{r.paymentMethod.replace(/_/g, ' ')}</Text>
          </View>
          <View style={styles.infoRow}>
            <Text style={styles.infoLabel}>Date:</Text>
            <Text style={styles.infoValue}>{new Date(r.paymentDate).toLocaleDateString()}</Text>
          </View>
          {r.bankReference && (
            <View style={styles.infoRow}>
              <Text style={styles.infoLabel}>Reference:</Text>
              <Text style={styles.infoValue}>{r.bankReference}</Text>
            </View>
          )}
        </View>

        {r.notes && (
          <View style={{ marginTop: 16 }}>
            <Text style={styles.sectionTitle}>Notes</Text>
            <Text>{r.notes}</Text>
          </View>
        )}

        {(r.companyChopUrl || r.signatureUrl) && (
          <View style={styles.signatureArea}>
            {r.companyChopUrl && (
              <View>
                <Text style={{ marginBottom: 4, color: '#666' }}>Company Chop</Text>
                <Image src={r.companyChopUrl} style={styles.stampImage} />
              </View>
            )}
            {r.signatureUrl && (
              <View>
                <Text style={{ marginBottom: 4, color: '#666' }}>Authorized Signature</Text>
                <Image src={r.signatureUrl} style={styles.sigImage} />
              </View>
            )}
          </View>
        )}

        <Text style={styles.footer}>Generated by HateBookkeeping</Text>
      </Page>
    </Document>
  );
}
